### ISSUE TITLE
 error: ‘CURLOPT_SSL_VERIFYSTATUS’ was not declared in this scope

### ISSUE THREAD

**Issue by stefanproell** [cloud-control/httpmon#2]
Hello,
when compiling I  received this error:
`
 $ make
g++ -g -std=c++0x -Wall -Werror -pedantic -Wno-vla    httpmon.cc  -lboost_program_options -lcurl -lpthread -Wl,-rpath,'${ORIGIN}' -o httpmon
In file included from httpmon.cc:9:0:
httpmon.cc: In function ‘int httpClientMain(int, ClientControl&, ClientData&)’:
httpmon.cc:272:27: error: ‘CURLOPT_SSL_VERIFYSTATUS’ was not declared in this scope
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYSTATUS, false);
                           ^
make: *** [httpmon] Error 1
`

I uncommented the line 272 like this to proceed:

//curl_easy_setopt(curl, CURLOPT_SSL_VERIFYSTATUS, false);

I use curl version curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

**Comment by cristiklein** [comment]
Hello,

Not sure what distribution and version of Linux you are using. In Ubuntu, you need to install one of the CURL SSL-related development packages, e.g., `libcurl4-nss-dev`.

Otherwise, if you do not plan to use `httpmon` with an SSL server, then it is okey to uncomment the line.

**Comment by stefanproell** [comment]
Hi,
thanks fpr your quick geply.
I am using an Ubuntu 14.04 LTS here and installed the missing library with
`sudo apt-get install libcurl4-nss-dev`
but still receive the same error. Do you have any further suggestions if I need SSL?

**Comment by cristiklein** [comment]
Hi,
According to the [manual](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYSTATUS.html), this option was only added in CURL 7.41.0, whereas Ubuntu 14.04 LTS [ships with](http://packages.ubuntu.com/trusty/libcurl4-nss-dev) CURL 7.35.0.
I see two options:
1. You update to a newer version of Ubuntu
2. You comment that line of code and use valid SSL certificates on the server, i.e., no self-signed, expired etc.
